Repository team-bofit/bofit-client, pull requests merged in 2025-10, with the labels that each got.

#436 Feat(client): 글 작성 - 이미지 업로드
  apps/client/package.json
  apps/client/src/pages/community/community-write/community-write.css.ts
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/widgets/community/components/community-image-uploader/community-image-uploader.css.ts
  apps/client/src/widgets/community/components/community-image-uploader/community-image-uploader.tsx
  apps/client/src/widgets/community/components/community-line/community-line.css.ts
  apps/client/src/widgets/community/components/community-line/community-line.tsx
  pnpm-lock.yaml
Labels: 💡 Feature, 지욱 🐝

#439 Feat(client): 대댓글 목록 조회 API 연동, 대댓글 삭제 API 연동
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/community/components/comment-input-box/comment-input-box.css.ts
  apps/client/src/widgets/community/components/community-modal/community-modal.tsx
  apps/client/src/widgets/community/components/feed-content/feed-content.tsx
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.css.ts
  apps/client/src/widgets/community/components/user-comment-info/user-comment-info.tsx
  apps/client/src/widgets/community/components/user-comment-list/user-comment-list.tsx
  apps/client/src/widgets/community/components/user-comment-reply/user-comment-reply.tsx
  apps/client/src/widgets/community/components/user-comment/user-comment.css.ts
  apps/client/src/widgets/community/components/user-comment/user-comment.tsx
  apps/client/src/widgets/community/constant/mock-user-comment-reply.ts
  apps/client/src/widgets/community/constant/modal-delete-content.ts
  apps/client/src/widgets/community/types/community-comment.type.ts
  apps/client/src/widgets/community/types/community-modal.type.ts
Labels: 💡 Feature, 정훈 🦁

#454 Feat(client): 커뮤니티 전체 글 좋아요 기능
  apps/client/src/widgets/community/components/feed-list-item/feed-list-item.css.ts
  apps/client/src/widgets/community/components/feed-list-item/feed-list-item.tsx
  apps/client/src/widgets/community/components/feed-list/feed-list.tsx
  apps/client/src/widgets/community/components/user-comment-list/user-comment-list.css.ts
  apps/client/src/widgets/community/components/user-comment-list/user-comment-list.tsx
Labels: 지우 ⛄, 💡 Feature

#452 Feat(client): 온보딩 페이지 기타정보 api 연결
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/onboarding/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/onboarding/components/step/etcetera-info/etcetera-info.tsx
  apps/client/src/widgets/onboarding/mocks/etc-mocks.ts
  apps/client/src/widgets/onboarding/schemas/onboarding-form-schema.ts
  apps/client/src/widgets/onboarding/type/user-info.type.ts
  apps/client/src/widgets/onboarding/utils/build-submit-payload.ts
Labels: 💡 Feature, 혜린 🐧
