Repository team-bofit/bofit-client, pull requests merged in 2025-07, with the labels that each got.

#20 Feat(client): useInputState 커스텀 훅 추가
  apps/client/src/shared/hooks/use-input-state.ts
Labels: 💡 Feature, 지욱 🐝

#23 Feat(client): SwitchCase 컴포넌트 구현
  apps/client/src/shared/components/.gitkeep
  apps/client/src/shared/components/switch-case.tsx
Labels: 💡 Feature, 지욱 🐝

#24 Init(client): 라우터 초기 세팅
  apps/client/package.json
  apps/client/src/app/App.tsx
  apps/client/src/pages/home/.gitkeep
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/router/routes/global-routes.tsx
  pnpm-lock.yaml
Labels: 혜린 🐧, ⚙️ Init

#28 Chore: discord 알림 .yml 파일 생성
  .github/workflows/discord-notify.yml
Labels: 💡 Feature, 정훈 🦁

#31 Init(client): Auto Build Github Action
  .github/workflows/build.js.yml
  apps/client/src/pages/home/home-page.tsx
Labels: 민정 🎱, 🤖 CI/CD

#30 Chore(project): README 작성
  README.md
Labels: 지욱 🐝, 🧹 Chore

#41 Feat(bds): Navigation 컴포넌트 구현
  packages/bds-ui/package.json
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/navigation/navigation.css.ts
  packages/bds-ui/src/components/navigation/navigation.tsx
  pnpm-lock.yaml
Labels: 지우 ⛄, 💡 Feature

#44 Fix(bds): 렌더링되지 않는 SVG 수정
  packages/bds-icon/src/icon/check.svg
  packages/bds-icon/src/icon/send.svg
  packages/bds-icon/src/icon/user.svg
Labels: 정훈 🦁, 💥 Fix

#34 Feat(bds): Chip 컴포넌트 구현
  README.md
  apps/client/src/pages/home/home-page.tsx
  packages/bds-ui/.storybook/main.ts
  packages/bds-ui/.storybook/preview.tsx
  packages/bds-ui/package.json
  packages/bds-ui/src/components/chip/chip.css.ts
  packages/bds-ui/src/components/chip/chip.stories.tsx
  packages/bds-ui/src/components/chip/chip.tsx
  packages/bds-ui/src/components/index.ts
Labels: 💡 Feature, 정훈 🦁

#48 Chore(bds): Chip 컴포넌트 주석 제거
  packages/bds-ui/src/components/chip/chip.stories.tsx
Labels: 🧹 Chore, 정훈 🦁, 💥 Fix

#46 Feat(bds): Button 컴포넌트
  packages/bds-ui/src/components/button/button.css.ts
  packages/bds-ui/src/components/button/button.stories.ts
  packages/bds-ui/src/components/button/button.stories.tsx
  packages/bds-ui/src/components/button/button.tsx
Labels: 💡 Feature, 민정 🎱

#52 Init(client): openApi 연동
  apps/client/package.json
  apps/client/src/shared/types/schema.d.ts
  pnpm-lock.yaml
Labels: 민정 🎱, ⚙️ Init

#53 Feat(bds): Title, Content 컴포넌트 구현
  packages/bds-ui/src/components/content/content.css.ts
  packages/bds-ui/src/components/content/content.stories.tsx
  packages/bds-ui/src/components/content/content.tsx
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/title/title.css.ts
  packages/bds-ui/src/components/title/title.stories.tsx
  packages/bds-ui/src/components/title/title.tsx
Labels: 💡 Feature, 정훈 🦁

#45 Feat(bds): Floating 컴포넌트 구현
  packages/bds-ui/src/components/floating/floating.css.ts
  packages/bds-ui/src/components/floating/floating.stories.tsx
  packages/bds-ui/src/components/floating/floating.tsx
  packages/bds-ui/src/components/index.ts
Labels: 💡 Feature, 수정 🐰

#61 Feat(bds): Indicator 컴포넌트 구현
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/indicator/indicator.css.ts
  packages/bds-ui/src/components/indicator/indicator.stories.tsx
  packages/bds-ui/src/components/indicator/indicator.tsx
  packages/bds-ui/src/icons/assets/page_selected.svg
  packages/bds-ui/src/icons/assets/page_unselected.svg
  packages/bds-ui/src/icons/icon-list.ts
  pnpm-lock.yaml
Labels: 지우 ⛄, 💡 Feature

#40 Feat(bds): Tab 컴포넌트 구현
  packages/bds-ui/package.json
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/tab/hooks/use-context.tsx
  packages/bds-ui/src/components/tab/hooks/use-tab-indicator.tsx
  packages/bds-ui/src/components/tab/tab.css.ts
  packages/bds-ui/src/components/tab/tab.stories.tsx
  packages/bds-ui/src/components/tab/tab.tsx
Labels: 💡 Feature, 혜린 🐧

#68 Feat(client): Graph 컴포넌트 구현
  apps/client/src/widgets/report/.gitkeep
  apps/client/src/widgets/report/component/graph/graph.css.ts
  apps/client/src/widgets/report/component/graph/graph.tsx
Labels: 💡 Feature, 혜린 🐧

#69 Feat(client): 정보입력 버튼 컴포넌트 구현
  apps/client/src/pages/onboarding/.gitkeep
  apps/client/src/widgets/onboarding/components/button/button.css.ts
  apps/client/src/widgets/onboarding/components/button/button.tsx
  packages/bds-ui/package.json
Labels: 지우 ⛄, 💡 Feature

#66 Feat(client): Community Alert 컴포넌트 구현
  apps/client/src/widgets/community/components/alert/alert.css.ts
  apps/client/src/widgets/community/components/alert/alert.tsx
  apps/client/src/widgets/community/constant/alert_content.ts
  packages/bds-ui/package.json
  packages/bds-ui/src/components/content/content.css.ts
  packages/bds-ui/src/components/content/content.tsx
Labels: 💡 Feature, 정훈 🦁

#74 Feat(client): HomeChip 컴포넌트 구현, design-system svg sprite package 수정, lineHeight 수정
  apps/client/src/widgets/home/chip/chip.css.ts
  apps/client/src/widgets/home/chip/chip.tsx
  packages/bds-ui/src/icons/assets/3d_brain.svg
  packages/bds-ui/src/icons/assets/3d_cancer.svg
  packages/bds-ui/src/icons/assets/3d_die.svg
  packages/bds-ui/src/icons/assets/3d_disability.svg
  packages/bds-ui/src/icons/assets/3d_heart.svg
  packages/bds-ui/src/icons/assets/3d_hospital.svg
  packages/bds-ui/src/icons/assets/3d_surgery.svg
  packages/bds-ui/src/icons/icon-list.ts
  packages/bds-ui/src/styles/tokens/color.css.ts
  packages/bds-ui/src/styles/tokens/font-style.ts
Labels: 💡 Feature, 정훈 🦁

#76 Feat(client): progress-bar 구현
  apps/client/src/widgets/onboarding/components/progress-bar/progress-bar.css.ts
  apps/client/src/widgets/onboarding/components/progress-bar/progress-bar.tsx
Labels: 💡 Feature, 수정 🐰

#88 Feat(client): 커뮤니티 empty 화면 퍼블리싱 및 floating컴포넌트 수정
  apps/client/src/pages/community/community-page.css.ts
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/widgets/community/components/empty-placeholder/empty-placeholder.css.ts
  apps/client/src/widgets/community/components/empty-placeholder/empty-placeholder.tsx
  apps/client/src/widgets/community/constant/empty-content.ts
  packages/bds-ui/src/components/floating/floating.css.ts
  packages/bds-ui/src/icons/assets/empty_writing.svg
  packages/bds-ui/src/icons/icon-list.ts
Labels: 💡 Feature, 정훈 🦁

#93 Feat(client): class 컴포넌트 구현
  apps/client/src/widgets/report/component/class/class.css.ts
  apps/client/src/widgets/report/component/class/class.tsx
Labels: 💡 Feature, 수정 🐰

#99 Feat(bds): Chip 컴포넌트 수정
  apps/client/.env.example
  apps/client/src/widgets/login/components/kakao-login-button/kakao-login-button.css.ts
  apps/client/src/widgets/login/components/kakao-login-button/kakao-login-button.tsx
  packages/bds-ui/src/components/chip/chip.css.ts
  packages/bds-ui/src/components/chip/chip.stories.tsx
  packages/bds-ui/src/components/chip/chip.tsx
  packages/bds-ui/src/icons/assets/kakaotalk.svg
  packages/bds-ui/src/icons/icon-list.ts
Labels: 지우 ⛄, 💡 Feature

#127 Feat(client): onboarding title component 구현
  apps/client/src/widgets/onboarding/components/title/title.css.ts
  apps/client/src/widgets/onboarding/components/title/title.tsx
Labels: 💡 Feature, 수정 🐰

#103 Feat(client): 커뮤니티 글 작성 페이지 퍼블리싱
  apps/client/index.html
  apps/client/src/pages/community/community-page.css.ts
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/pages/community/community-write/community-write.css.ts
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/constants/text_limits.ts
  apps/client/src/shared/hooks/use-limited-input.tsx
  apps/client/src/shared/hooks/use-mobile-submit.tsx
  apps/client/src/shared/hooks/use-textarea-state.ts
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/routes/global-routes.tsx
  apps/client/src/widgets/community/components/community-line/community-line.css.ts
  apps/client/src/widgets/community/components/community-line/community-line.tsx
  apps/client/src/widgets/community/constant/alert-content.ts
  apps/client/src/widgets/community/constant/community-line-placeholder.ts
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/input/input.css.ts
  packages/bds-ui/src/components/input/input.stories.tsx
  packages/bds-ui/src/components/input/input.tsx
Labels: 💡 Feature, 정훈 🦁

#145 Feat(client): onboarding loading component 구현
  apps/client/package.json
  apps/client/public/glass_icon_logo_animation.json
  apps/client/src/widgets/onboarding/components/matching-loader/matching-loader.css.ts
  apps/client/src/widgets/onboarding/components/matching-loader/matching-loader.tsx
  pnpm-lock.yaml
Labels: 💡 Feature, 수정 🐰

#144 Feat(client): 커뮤니티 댓글 작성 컴포넌트 구현
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/widgets/community/components/comment-box/comment-box.css.ts
  apps/client/src/widgets/community/components/comment-box/comment-box.tsx
  apps/client/src/widgets/community/constant/input-placeholder.ts
  packages/bds-ui/src/components/input/input.css.ts
  packages/bds-ui/src/components/input/input.tsx
  packages/bds-ui/src/icons/assets/btn_comment.svg
  packages/bds-ui/src/icons/icon-list.ts
Labels: 💡 Feature, 정훈 🦁

#138 Feat(client): Insurance Title, Subtitle 컴포넌트 구현
  apps/client/src/shared/components/insurance-subtitle/insurance-subtitle.css.ts
  apps/client/src/shared/components/insurance-subtitle/insurance-subtitle.tsx
  apps/client/src/shared/components/insurance-title/insurance-title.css.ts
  apps/client/src/shared/components/insurance-title/insurance-title.tsx
Labels: 지우 ⛄, 💡 Feature

#151 Feat(client): favicon 세팅
  apps/client/index.html
  apps/client/public/favicon.svg
Labels: 지욱 🐝, 🧹 Chore

#154 Feat(bds): textbutton 의 white variant 추가
  packages/bds-ui/src/components/text-button/text-button.css.ts
  packages/bds-ui/src/components/text-button/text-button.stories.tsx
  packages/bds-ui/src/components/text-button/text-button.tsx
Labels: 💡 Feature, 민정 🎱

#139 Feat(client): onboarding horizontal button 구현
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.css.ts
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.tsx
Labels: 💡 Feature, 수정 🐰

#146 Feat(client): 로그인 플로우 퍼블리싱
  apps/client/package.json
  apps/client/public/community_preview.webp
  apps/client/public/report_preview.webp
  apps/client/src/pages/login/login-page.tsx
  apps/client/src/shared/auth/services/token-service.ts
  apps/client/src/widgets/login/components/.gitkeep
  apps/client/src/widgets/login/components/kakao-login-button/kakao-login-button.css.ts
  apps/client/src/widgets/login/components/kakao-login-button/kakao-login-button.tsx
  apps/client/src/widgets/login/components/login-slide/kakao-login-button.css.ts
  apps/client/src/widgets/login/components/login-slide/kakao-login-button.tsx
  apps/client/src/widgets/login/components/login-slide/kakao-login-modal.tsx
  apps/client/src/widgets/login/components/login-slide/login-slide.css.ts
  apps/client/src/widgets/login/components/login-slide/login-slide.tsx
  apps/client/src/widgets/login/components/login-slide/sub-title.css.ts
  apps/client/src/widgets/login/components/login-slide/sub-title.tsx
  apps/client/src/widgets/login/components/login-slide/title.css.ts
  apps/client/src/widgets/login/components/login-slide/title.tsx
  apps/client/src/widgets/login/constants/login-content.ts
  config/eslint/.eslintrc.cjs
  packages/bds-ui/src/components/indicator/indicator.tsx
  packages/bds-ui/src/components/modal/modal-container.css.ts
  packages/bds-ui/src/components/modal/modal.css.ts
  packages/bds-ui/src/components/modal/modal.tsx
  packages/bds-ui/src/icons/assets/check.svg
  packages/bds-ui/src/styles/global.css.ts
  pnpm-lock.yaml
Labels: 💡 Feature, 지욱 🐝

#147 Feat(client): 큰 병 컴포넌트 구현 및 Divider 컴포넌트 구현
  apps/client/src/widgets/report/components/divider/divider.css.ts
  apps/client/src/widgets/report/components/divider/divider.tsx
  apps/client/src/widgets/report/components/graph/graph.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/cancer.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/noehyeolgwan.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/shimjang.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/style.css.ts
  apps/client/src/widgets/report/components/keunbyeong/hooks/use-coverage.tsx
  apps/client/src/widgets/report/components/keunbyeong/keunbyeong.css.ts
  apps/client/src/widgets/report/components/keunbyeong/keunbyeong.tsx
  apps/client/src/widgets/report/components/keunbyeong/mocks/keunbyeong-mocks.ts
  apps/client/src/widgets/report/constant/alert-content.ts
Labels: 💡 Feature, 혜린 🐧

#158 Feat(client): 로딩 fallback 페이지 구현
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/assets/glass_icon_logo_animation.json
  apps/client/src/shared/components/loading/loading.tsx
  apps/client/src/shared/router/global-error-boundary.tsx
  apps/client/src/widgets/onboarding/components/matching-loader/matching-loader.css.ts
  apps/client/src/widgets/onboarding/components/matching-loader/matching-loader.tsx
Labels: 💡 Feature, 지욱 🐝

#166 Feat(client): 입원 컴포넌트 구현
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/widgets/report/components/ipwon/components/jilbyeong.tsx
  apps/client/src/widgets/report/components/ipwon/components/sanghae.tsx
  apps/client/src/widgets/report/components/ipwon/ipwon.css.ts
  apps/client/src/widgets/report/components/ipwon/ipwon.tsx
  packages/bds-ui/src/components/alert/alert.css.ts
  packages/bds-ui/src/components/alert/alert.tsx
Labels: 💡 Feature, 혜린 🐧

#171 Feat(client): home page 구현
  apps/client/public/3Dicon_background.webp
  apps/client/public/3Dicon_background_glass.webp
  apps/client/public/home_default_3D_logo.png
  apps/client/src/pages/home/home-page.css.ts
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/components/insurance-subtitle/insurance-subtitle.tsx
  apps/client/src/widgets/home/components/community-link/community-link.css.ts
  apps/client/src/widgets/home/components/features-section/features-section.css.ts
  apps/client/src/widgets/home/components/features-section/features-section.tsx
  apps/client/src/widgets/home/components/home-chip/home-chip.css.ts
  apps/client/src/widgets/home/components/home-chip/home-chip.tsx
  apps/client/src/widgets/home/components/home-top-section/home-top-section.css.ts
  apps/client/src/widgets/home/components/home-top-section/home-top-section.tsx
  apps/client/src/widgets/home/components/info-section/info-section.css.ts
  apps/client/src/widgets/home/components/info-section/info-section.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.css.ts
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  apps/client/src/widgets/home/components/tip/tip.css.ts
  packages/bds-ui/package.json
  packages/bds-ui/src/components/chip/chip.css.ts
  packages/bds-ui/src/components/chip/chip.stories.tsx
  packages/bds-ui/src/components/chip/chip.tsx
  packages/bds-ui/src/components/text-button/text-button.css.ts
  packages/bds-ui/src/icons/assets/logotype_white.svg
  packages/bds-ui/src/icons/assets/user.svg
  packages/bds-ui/src/icons/icon-list.ts
  packages/bds-ui/src/styles/tokens/z-index.ts
  pnpm-lock.yaml
Labels: 💡 Feature, 민정 🎱

#168 Feat(client): funnel step file 생성 및 구조 잡기
  apps/client/src/pages/onboarding/onboarding-page.css.ts
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.tsx
  apps/client/src/widgets/onboarding/components/start-content/start-content.tsx
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.css.ts
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.tsx
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.tsx
  apps/client/src/widgets/onboarding/components/step/matching-loader/matching-loader.css.ts
  apps/client/src/widgets/onboarding/components/step/matching-loader/matching-loader.tsx
  apps/client/src/widgets/onboarding/components/step/price-info/price-info.tsx
  apps/client/src/widgets/onboarding/components/step/start-content/start-content.css.ts
  apps/client/src/widgets/onboarding/components/step/start-content/start-content.tsx
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.tsx
  packages/bds-ui/src/components/text-button/text-button.css.ts
  packages/bds-ui/src/components/toast/toast-container.css.ts
Labels: 💡 Feature, 수정 🐰

#188 HOTFIX(client): 커뮤니티 프리뷰 이미지 변경
  apps/client/public/community_preview.webp
Labels: 지욱 🐝, 🚨 HOTFIX

#155 Feat(client): 커뮤니티 디테일 페이지 구현
  apps/client/src/pages/community/community-detail/community-detail.css.ts
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/routes/global-routes.tsx
  apps/client/src/widgets/community/components/comment-box/comment-box.css.ts
  apps/client/src/widgets/community/components/post-detail-info/post-detail-info.css.ts
  apps/client/src/widgets/community/components/post-detail-info/post-detail-info.tsx
  apps/client/src/widgets/community/components/user-comment/user-comment.css.ts
  apps/client/src/widgets/community/components/user-comment/user-comment.tsx
  apps/client/src/widgets/community/components/user-detail-meta/user-detail-meta.css.ts
  apps/client/src/widgets/community/components/user-detail-meta/user-detail-meta.tsx
  apps/client/src/widgets/community/mocks/community-detail-comment-data.ts
  apps/client/src/widgets/community/mocks/community-detail-data.ts
  packages/bds-ui/src/components/button/button.css.ts
  packages/bds-ui/src/components/modal/modal.css.ts
  packages/bds-ui/src/icons/components/icon.tsx
Labels: 💡 Feature, 정훈 🦁

#169 Feat(client) 커뮤니티 페이지 Mock 데이터 추가
  apps/client/src/pages/community/community-page.css.ts
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/shared/constants/bullet.ts
  apps/client/src/widgets/community/components/detail-comment/detail-comment.css.ts
  apps/client/src/widgets/community/components/detail-comment/detail-comment.tsx
  apps/client/src/widgets/community/constant/detail-content.ts
  apps/client/src/widgets/community/mocks/community-post-data.ts
  apps/client/src/widgets/community/utils/getTimeAgo.ts
  packages/bds-ui/src/components/content/content.css.ts
  packages/bds-ui/src/components/floating/floating.css.ts
  packages/bds-ui/src/components/title/title.css.ts
Labels: 💡 Feature, 정훈 🦁

#187 Feat(client): onboarding 정보입력 step1, step2, step3 구현
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/shared/hooks/use-click-outside.ts
  apps/client/src/shared/hooks/use-user-info-valid.ts
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.css.ts
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.tsx
  apps/client/src/widgets/onboarding/components/dropdown/dropdown.tsx
  apps/client/src/widgets/onboarding/components/dropdown/option-item.tsx
  apps/client/src/widgets/onboarding/components/grid-button-section/grid-button-section.tsx
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.tsx
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.tsx
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.css.ts
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.tsx
  apps/client/src/widgets/onboarding/components/step/matching-loader/matching-loader.tsx
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.css.ts
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.tsx
  apps/client/src/widgets/onboarding/mocks/user-info.mock.ts
  apps/client/src/widgets/onboarding/type/user-info.type.ts
  packages/bds-ui/src/components/input/input.tsx
Labels: 💡 Feature, 수정 🐰

#196 Feat(bds): Slider 컴포넌트
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/slider/hooks/use-slider.tsx
  packages/bds-ui/src/components/slider/slider.css.ts
  packages/bds-ui/src/components/slider/slider.stories.tsx
  packages/bds-ui/src/components/slider/slider.tsx
Labels: 💡 Feature, 민정 🎱

#185 Feat(client): 보험 추천 리포트 페이지 퍼블리싱
  apps/client/src/pages/report/report-page.css.ts
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/widgets/report/components/accordion/accordion.css.ts
  apps/client/src/widgets/report/components/accordion/accordion.tsx
  apps/client/src/widgets/report/components/report-detail/report-detail.css.ts
  apps/client/src/widgets/report/components/report-detail/report-detail.tsx
  apps/client/src/widgets/report/components/samang/samang.css.ts
  apps/client/src/widgets/report/components/summarize/summarize.css.ts
  apps/client/src/widgets/report/hooks/use-move-scroll.tsx
  packages/bds-ui/src/components/navigation/navigation.css.ts
  packages/bds-ui/src/components/tab/tab.tsx
Labels: 💡 Feature, 혜린 🐧

#202 Feat(client): Summarize 컴포넌트 api 연동
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/shared/api/domain/mypage/queries.ts
  apps/client/src/shared/api/domain/report/queries.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/constants/end-point.ts
  apps/client/src/shared/constants/query-key.ts
  apps/client/src/widgets/report/components/summarize/summarize.tsx
Labels: 지우 ⛄, 💡 Feature

#213 Refactor(client): api 연동 관련 파일 위치 변경
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/mypage/queries.ts
  apps/client/src/shared/api/domain/report/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/keys/query.key.ts
  apps/client/src/shared/constants/text-limits.ts
Labels: 지우 ⛄, 🔨 Refactor

#204 Feat(client): 커뮤니티 게시글 작성 api 연동
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/widgets/community/components/detail-comment/detail-comment.css.ts
Labels: 💡 Feature, 지욱 🐝

#206 Feat(client): onboarding 정보입력 직업 목록 조회 api 연동
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/onboarding/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/hooks/use-user-info-valid.ts
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.tsx
  apps/client/src/widgets/onboarding/components/dropdown/dropdown.tsx
  apps/client/src/widgets/onboarding/components/dropdown/option-item.tsx
  apps/client/src/widgets/onboarding/components/grid-button-section/grid-button-section.tsx
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.tsx
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.tsx
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.tsx
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.tsx
  apps/client/src/widgets/onboarding/mocks/user-info.mock.ts
  apps/client/src/widgets/onboarding/type/user-info.type.ts
Labels: 💡 Feature, 수정 🐰

#219 Feat(client): 스크롤 move 관련 hook 추가
  apps/client/src/shared/hooks/use-move-scroll.ts
  apps/client/src/widgets/onboarding/components/dropdown/dropdown.tsx
Labels: 💡 Feature, 수정 🐰

#218 Feat(client): 질병, 보장 목록 get api 연결
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/onboarding/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.tsx
  apps/client/src/widgets/onboarding/components/dropdown/dropdown.tsx
  apps/client/src/widgets/onboarding/components/grid-button-section/grid-button-section.tsx
  apps/client/src/widgets/onboarding/components/horizontal-button/horizontal-button.tsx
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.tsx
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.tsx
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.tsx
  apps/client/src/widgets/onboarding/mocks/user-info.mock.ts
  apps/client/src/widgets/onboarding/type/user-info.type.ts
Labels: 💡 Feature, 수정 🐰

#216 Feat(client): 보험 추천 리포트 큰병 조회 api 연동
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/report/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/widgets/report/components/accordion/accordion.tsx
  apps/client/src/widgets/report/components/graph/graph.tsx
  apps/client/src/widgets/report/components/info/info.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/cancer.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/noehyeolgwan.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/shimjang.tsx
  apps/client/src/widgets/report/components/keunbyeong/hooks/use-coverage.tsx
  apps/client/src/widgets/report/components/keunbyeong/keunbyeong.tsx
  apps/client/src/widgets/report/components/keunbyeong/mocks/keunbyeong-mocks.ts
  apps/client/src/widgets/report/components/title/title.tsx
  apps/client/src/widgets/report/constant/alert-content.ts
Labels: 💡 Feature, 혜린 🐧

#221 Fix(client): suspense 로딩이 전역적으로 적용이 되지 않는 문제 해결
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/shared/router/layout-free-layout.tsx
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/routes/global-routes.tsx
  apps/client/src/widgets/home/components/features-section/features-section.css.ts
  apps/client/src/widgets/home/components/features-section/features-section.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.css.ts
Labels: 민정 🎱, 💥 Fix

#231 Feat(client): 정보 입력 페이지 유저 정보 조회 api 연동
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/shared/api/domain/onboarding/queries.ts
  apps/client/src/widgets/onboarding/components/step/matching-loader/matching-loader.tsx
  apps/client/src/widgets/onboarding/components/step/start-content/start-content.tsx
  apps/client/src/widgets/onboarding/mocks/user-info.mock.ts
Labels: 지우 ⛄, 💡 Feature

#210 Feat(client): 가장 최근에 추천 받은 보험 리포트의 요약 내용을 조회하는 api 연동
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/home/queries.ts
  apps/client/src/shared/api/domain/mypage/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/configs/app-config.ts
  apps/client/src/widgets/home/components/home-chip/home-chip.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.css.ts
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  apps/client/src/widgets/home/configs/home-chip-config.ts
Labels: 💡 Feature, 민정 🎱

#229 Feat(client): 최근 추천 리포트 요약 조회 api 연동
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/report/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
Labels: 지우 ⛄, 💡 Feature

#225 Feat(client): 커뮤니티 상세 조회 API 연동
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/widgets/community/components/detail-comment/detail-comment.tsx
  apps/client/src/widgets/community/components/user-detail-meta/user-detail-meta.tsx
  apps/client/src/widgets/community/mocks/community-detail-data.ts
  apps/client/src/widgets/community/utils/get-time-ago.ts
Labels: 💡 Feature, 정훈 🦁

#235 Chore(client): 보험 추천 리포트 username 본명으로 변경
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/report/components/summarize/summarize.tsx
Labels: 지우 ⛄, 🧹 Chore

#240 HOTFIX: 로그인 리다이렉트 문제 해결
  apps/client/src/pages/login-fallback/login-fallback-page.tsx
Labels: 지우 ⛄, 🚨 HOTFIX

#245 Feat(client): 커뮤니티 댓글 작성 API 연동
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/widgets/community/components/comment-box/comment-box.tsx
Labels: 💡 Feature, 정훈 🦁

#253 Fix(client): home 에서 버그를 해결합니다.
  apps/client/src/pages/home/home-page.css.ts
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/router/routes/global-routes.tsx
  apps/client/src/shared/router/routes/layout-free-routes.tsx
  apps/client/src/widgets/home/components/features-section/features-section.css.ts
  apps/client/src/widgets/home/components/features-section/features-section.tsx
  apps/client/src/widgets/home/components/info-section/info-section.css.ts
  apps/client/src/widgets/home/components/info-section/info-section.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
Labels: 민정 🎱, 💥 Fix

#249 Feat(client): 내 글 및 내 댓글 api 연동
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/shared/api/config/end-point.ts
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/domain/mypage/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/hooks/use-intersection-observer.tsx
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/mypage/body.tsx
  apps/client/src/widgets/mypage/comment-preview.css.ts
  apps/client/src/widgets/mypage/comment-preview.tsx
  apps/client/src/widgets/mypage/post-preview.css.ts
  apps/client/src/widgets/mypage/post-preview.tsx
  apps/client/src/widgets/mypage/preview.css.ts
  apps/client/src/widgets/mypage/preview.tsx
  packages/bds-ui/src/components/content/content.css.ts
  packages/bds-ui/src/components/tab/hooks/use-tab-indicator.tsx
  packages/bds-ui/src/components/tab/tab.tsx
  packages/bds-ui/src/components/title/title.css.ts
  packages/bds-ui/src/components/title/title.tsx
  pnpm-lock.yaml
Labels: 💡 Feature, 지욱 🐝

#259 Feat(client): 인증 기능 활성화
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/shared/configs/app-config.ts
Labels: 💡 Feature, 민정 🎱

#260 Refactor(client): accordion 컴포넌트 icon 회전 방향 수정
  apps/client/src/widgets/report/components/accordion/accordion.css.ts
  apps/client/src/widgets/report/components/accordion/accordion.tsx
Labels: 지우 ⛄, 🔨 Refactor

#255 Refactor(client): navigation onclick props 추가
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/pages/community/community-page.tsx
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/pages/home/home-page.tsx
  apps/client/src/pages/my/my-page.tsx
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/pages/report/report-page.tsx
  packages/bds-ui/src/components/navigation/navigation.stories.tsx
  packages/bds-ui/src/components/navigation/navigation.tsx
Labels: 지우 ⛄, 🔨 Refactor

#268 Fix(client): QA 시작 전 수정
  apps/client/src/shared/router/routes/protected-route.tsx
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/report/components/report-detail/report-detail.tsx
Labels: 🚨 HOTFIX

#275 QA-1: 스타일 수정
  apps/client/src/widgets/mypage/body.tsx
  apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.tsx
  apps/client/src/widgets/report/components/recommend/recommend.css.ts
  apps/client/src/widgets/report/components/recommend/recommend.tsx
Labels: 지우 ⛄, 💥 Fix

#280 [QA-1] 보험 추천 리포트 페이지 QA 반영
  apps/client/src/widgets/report/components/accordion/accordion.css.ts
  apps/client/src/widgets/report/components/accordion/accordion.tsx
  apps/client/src/widgets/report/components/ipwon/components/jilbyeong.tsx
  apps/client/src/widgets/report/components/ipwon/components/sanghae.tsx
  apps/client/src/widgets/report/components/janghae/components/jilbyeong.tsx
  apps/client/src/widgets/report/components/janghae/components/sanghae.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/cancer.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/noehyeolgwan.tsx
  apps/client/src/widgets/report/components/keunbyeong/components/shimjang.tsx
  apps/client/src/widgets/report/components/report-detail/report-detail.tsx
  apps/client/src/widgets/report/components/samang/components/jilbyeong.tsx
  apps/client/src/widgets/report/components/samang/components/sanghae.tsx
  apps/client/src/widgets/report/components/susul/components/jilbyeong-class.tsx
  apps/client/src/widgets/report/components/susul/components/jilbyeong.tsx
  apps/client/src/widgets/report/components/susul/components/sanghae-class.tsx
  apps/client/src/widgets/report/components/susul/components/sanghae.tsx
  apps/client/src/widgets/report/constant/alert-content.ts
Labels: 혜린 🐧, 💥 Fix

#286 QA-1: 모바일 엔터키 done을 엔터로 수정
  apps/client/index.html
Labels: 정훈 🦁, 💥 Fix

#292 QA-1: 리포트 없을 시, 마이페이지 화면 다르게
  apps/client/src/pages/my/my-page.tsx
  apps/client/src/widgets/home/components/info-section/info-section.tsx
  apps/client/src/widgets/mypage/body.tsx
Labels: 지우 ⛄, 💡 Feature

#290 QA-1: home 페이지 chip type extends , cursor 제거
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  apps/client/src/widgets/home/components/tip/tip.css.ts
  packages/bds-ui/src/components/chip/chip.tsx
Labels: 민정 🎱, 💥 Fix

#298 QA-1: 보험 추천 리포트 페이지 스크롤시 자동 Tab 선택
  apps/client/src/widgets/report/components/report-detail/report-detail.tsx
  apps/client/src/widgets/report/constant/section-component-constant.ts
  apps/client/src/widgets/report/constant/tab-constant.ts
  apps/client/src/widgets/report/hooks/tab-sync.tsx
  apps/client/src/widgets/report/hooks/use-move-scroll.tsx
  packages/bds-ui/src/components/tab/tab.css.ts
  packages/bds-ui/src/components/tab/tab.tsx
Labels: 혜린 🐧, 💥 Fix

#300 feat: 글씨 눌렀을 떄도 checkbox 체크
  apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.css.ts
  apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.tsx
  packages/bds-ui/src/components/modal/modal.css.ts
  packages/bds-ui/src/components/modal/modal.tsx
Labels: 지우 ⛄, 💡 Feature

#305 HOFIX: 커뮤니티 디테일 페이지 스타일 수정
  apps/client/src/pages/community/community-detail/community-detail.css.ts
  apps/client/src/pages/community/community-detail/community-detail.tsx
  apps/client/src/pages/community/community-page.css.ts
  apps/client/src/pages/community/community-page.tsx
Labels: 🚨 HOTFIX, 정훈 🦁

#306 Project: README 업데이트
  README.md
Labels: 지욱 🐝, 🧹 Chore

#312 Fix(client): 로그인 페이지 이미지 변경
  apps/client/public/community_preview.png
  apps/client/public/community_preview.svg
  apps/client/public/report_preview.png
  apps/client/public/report_preview.svg
  apps/client/src/widgets/login/constants/login-content.ts
Labels: 지우 ⛄, 💥 Fix

#320 Feat(client): 모바일 확대방지
  apps/client/index.html
Labels: 💡 Feature, 지욱 🐝

#321 Production-release(v.1.0.0)
  apps/client/index.html
Labels: 지욱 🐝, 🚀 Deploy

#325 Feat(client): onboarding url 방어
  apps/client/src/pages/onboarding/onboarding-page.tsx
Labels: 💡 Feature, 지욱 🐝

#330 Production-release(v.1.0.0)
  apps/client/src/pages/report/report-page.tsx
  apps/client/src/widgets/report/components/accordion/accordion.css.ts
  packages/bds-ui/src/components/input/input.tsx
Labels: 지욱 🐝, 🚀 Deploy

#342 Refactor(client): 커뮤니티 쿼리키 통합
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/keys/query-key.ts
  apps/client/src/widgets/login/components/login-slide/login-slide.tsx
Labels: 지욱 🐝, 🔨 Refactor

#343 Chore(project): README 최신화
  README.md
Labels: 🧹 Chore, 정훈 🦁

#340 CI/CD(*): ChangeSet setting (version control)
  .changeset/README.md
  .changeset/config.json
  .changeset/tall-lemons-join.md
  .github/workflows/release.yml
  .gitignore
  CHANGESETS.md
  package.json
  pnpm-lock.yaml
Labels: 민정 🎱, 🤖 CI/CD

#351 Fix(client): 마이페이지 navigate 버튼 로직 수정
  apps/client/src/pages/my/my-page.tsx
Labels: 지욱 🐝, 💥 Fix

#354 Feat(client): 카카오 로그인 URL 및 리다이렉트 URI 로컬 & 배포 환경 설정 추가
  apps/client/.env.example
  apps/client/src/shared/configs/app-config.ts
  apps/client/src/widgets/login/components/login-slide/kakao-login-button.tsx
Labels: 💡 Feature, 지욱 🐝
