Repository team-bofit/bofit-client, pull requests merged in 2025-06, with the labels that each got.

#6 Init(project): 폴더 구조 세팅
  apps/client/index.html
  apps/client/src/app/App.css
  apps/client/src/app/App.tsx
  apps/client/src/app/index.css
  apps/client/src/app/main.tsx
  apps/client/src/pages/community/page.tsx
  apps/client/src/pages/home/.gitkeep
  apps/client/src/pages/landing/.gitkeep
  apps/client/src/pages/mypage/.gitkeep
  apps/client/src/pages/onboarding/.gitkeep
  apps/client/src/pages/report/.gitkeep
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/shared/api/domain/home/queries.ts
  apps/client/src/shared/api/domain/landing/queries.ts
  apps/client/src/shared/api/domain/mypage/queries.ts
  apps/client/src/shared/api/domain/onboarding/queries.ts
  apps/client/src/shared/api/domain/report/queries.ts
  apps/client/src/shared/api/keys/query.key.ts
  apps/client/src/shared/api/types/types.ts
  apps/client/src/shared/components/.gitkeep
  apps/client/src/shared/configs/.gitkeep
  apps/client/src/shared/hooks/.gitkeep
  apps/client/src/shared/utils/.gitkeep
  apps/client/src/widgets/community/components/.gitkeep
  apps/client/src/widgets/community/configs/.gitkeep
  apps/client/src/widgets/community/hooks/.gitkeep
  apps/client/src/widgets/community/utils/.gitkeep
  apps/client/src/widgets/home/.gitkeep
  apps/client/src/widgets/landing/.gitkeep
  apps/client/src/widgets/mypage/.gitkeep
  apps/client/src/widgets/onboarding/.gitkeep
  apps/client/src/widgets/report/.gitkeep
Labels: 민정 🎱, ⚙️ Init

#5 Init(client): 절대 경로 설정
  apps/client/package.json
  apps/client/src/app/App.tsx
  apps/client/src/pages/community/CommunityPage.tsx
  apps/client/src/pages/community/page.tsx
  apps/client/tsconfig.json
  apps/client/vite.config.ts
  config/eslint/.eslintrc.cjs
  pnpm-lock.yaml
Labels: 🧹 Chore, 정훈 🦁

#13 Init(client): ky 세팅
  apps/client/package.json
  apps/client/src/shared/api/config/instance.ts
  pnpm-lock.yaml
Labels: 수정 🐰, ⚙️ Init
