Repository team-bofit/bofit-client, pull requests merged in 2025-09, with the labels that each got.

#372 Feat(bds): alert 컴포넌트 스토리북 작성
  packages/bds-ui/src/components/alert/alert.css.ts
  packages/bds-ui/src/components/alert/alert.stories.tsx
  packages/bds-ui/src/components/alert/alert.tsx
Labels: 💡 Feature, 혜린 🐧

#375 Version-Contol(v._)
  .changeset/breezy-windows-cry.md
Labels: 민정 🎱, 🚀 Deploy

#376 Feat(bds): LikeButton 컴포넌트 구현
  packages/bds-ui/src/components/index.ts
  packages/bds-ui/src/components/like-button/like-button.css.ts
  packages/bds-ui/src/components/like-button/like-button.stories.tsx
  packages/bds-ui/src/components/like-button/like-button.tsx
Labels: 💡 Feature, 정훈 🦁

#380 Refactor(client): 로그인 api 리팩터링
  apps/client/src/pages/login-fallback/login-fallback-page.tsx
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/login-fallback/hooks/use-social-login.ts
Labels: 지우 ⛄, 🔨 Refactor

#369 Refactor(client): chip 중복 네이밍 리펙토링
  apps/client/src/widgets/home/components/home-card/home-card.css.ts
  apps/client/src/widgets/home/components/home-card/home-card.tsx
  apps/client/src/widgets/home/components/info-section/info-section.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  apps/client/src/widgets/report/components/accordion/accordion.tsx
  apps/client/src/widgets/report/components/chip/chip.tsx
Labels: 민정 🎱, 🔨 Refactor

#394 Refactor(bds): 텍스트 버튼 수정 사항 반영 및 size 베리에이션 추가
  apps/client/src/pages/community/community-edit/community-edit.tsx
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/widgets/community/components/user-comment/user-comment.tsx
  apps/client/src/widgets/community/components/user-detail-meta/user-detail-meta.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  packages/bds-ui/.storybook/preview.tsx
  packages/bds-ui/src/components/text-button/text-button.css.ts
  packages/bds-ui/src/components/text-button/text-button.stories.tsx
  packages/bds-ui/src/components/text-button/text-button.tsx
Labels: 지욱 🐝, 🔨 Refactor

#398 Refactor(client): 컴포넌트 색상 변경
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/widgets/community/components/user-detail-meta/user-detail-meta.tsx
Labels: 지우 ⛄, 🔨 Refactor

#404 Fix(client): 서빙 데이터 스키마 싱크 문제 임시 해결
  apps/client/src/pages/community/community-edit/community-edit.tsx
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/types/schema.d.ts
Labels: 민정 🎱, 💥 Fix

#384 Refactor(client): 온보딩 페이지 Refactor
  apps/client/src/pages/onboarding/onboarding-page.css.ts
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.tsx
  apps/client/src/widgets/onboarding/components/grid-button-section/grid-button-section.tsx
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.css.ts
  apps/client/src/widgets/onboarding/components/step/coverage-info/coverage-info.tsx
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.css.ts
  apps/client/src/widgets/onboarding/components/step/health-info/health-info.tsx
  apps/client/src/widgets/onboarding/components/step/price-info/price-info.css.ts
  apps/client/src/widgets/onboarding/components/step/price-info/price-info.tsx
  apps/client/src/widgets/onboarding/components/step/start-content/start-content.css.ts
  apps/client/src/widgets/onboarding/components/step/start-content/start-content.tsx
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.css.ts
  apps/client/src/widgets/onboarding/components/step/user-info/user-info.tsx
Labels: 혜린 🐧, 🔨 Refactor

#409 HOTFIX(client): 온보딩 페이지 matching 단계 Navigation 나타남 해결
  apps/client/src/pages/onboarding/onboarding-page.tsx
Labels: 🚨 HOTFIX, 혜린 🐧

#412 Feat(client): 필터 드롭다운 컴포넌트 및 useToggle 훅 추가
  apps/client/src/shared/hooks/use-toggle.ts
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.css.ts
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.tsx
Labels: 💡 Feature, 지욱 🐝

#425 Fix(bds): storybook 배포 오류 해결
  apps/client/public/3d_brain.webp
  apps/client/public/3d_cancer.webp
  apps/client/public/3d_die.webp
  apps/client/public/3d_disability.webp
  apps/client/public/3d_heart.webp
  apps/client/public/3d_hospital.webp
  apps/client/public/3d_icon_logo.webp
  apps/client/public/3d_surgery.webp
  apps/client/public/glass_icon_bulb.svg
  apps/client/public/glass_icon_bulb.webp
  apps/client/public/glass_icon_chat.webp
  apps/client/public/glass_icon_chat_dark.webp
  apps/client/public/logo_3d.webp
  apps/client/public/logotype_3d.webp
  apps/client/src/pages/splash/splash-page.css.ts
  apps/client/src/pages/splash/splash-page.tsx
  apps/client/src/widgets/home/components/info-section/info-section.tsx
  apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
  apps/client/src/widgets/home/components/tip/tip.css.ts
  apps/client/src/widgets/home/components/tip/tip.tsx
  apps/client/src/widgets/home/configs/home-chip-config.ts
  packages/bds-ui/src/icons/assets/3D_icon_add_inform.svg
  packages/bds-ui/src/icons/assets/3D_icon_logo.svg
  packages/bds-ui/src/icons/assets/3D_icon_shield.svg
  packages/bds-ui/src/icons/assets/3d_brain.svg
  packages/bds-ui/src/icons/assets/3d_cancer.svg
  packages/bds-ui/src/icons/assets/3d_die.svg
  packages/bds-ui/src/icons/assets/3d_disability.svg
  packages/bds-ui/src/icons/assets/3d_heart.svg
  packages/bds-ui/src/icons/assets/3d_hospital.svg
  packages/bds-ui/src/icons/assets/3d_surgery.svg
  packages/bds-ui/src/icons/assets/logo_3d.svg
  packages/bds-ui/src/icons/assets/logotype_3d.svg
  packages/bds-ui/src/icons/icon-list.ts
Labels: 수정 🐰, 💥 Fix

#417 Feat(client): 댓글 컴포넌트 사진 추가 및 대댓글 보기 구현
  apps/client/src/widgets/community/components/user-comment-info/user-comment-info.css.ts
  apps/client/src/widgets/community/components/user-comment-info/user-comment-info.tsx
  apps/client/src/widgets/community/components/user-comment-list/user-comment-list.tsx
  apps/client/src/widgets/community/components/user-comment/user-comment.css.ts
  apps/client/src/widgets/community/components/user-comment/user-comment.tsx
  apps/client/src/widgets/community/types/community-comment.type.ts
  packages/bds-ui/src/components/text-button/text-button.css.ts
  packages/bds-ui/src/components/text-button/text-button.stories.tsx
Labels: 💡 Feature, 정훈 🦁

#423 Feat(client): 대댓글 컴포넌트 구현
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/api/domain/community/queries.ts
  apps/client/src/widgets/community/components/.gitkeep
  apps/client/src/widgets/community/components/community-modal/community-modal.tsx
  apps/client/src/widgets/community/components/feed-content/feed-content.tsx
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.css.ts
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.tsx
  apps/client/src/widgets/community/components/user-comment-list/user-comment-list.tsx
  apps/client/src/widgets/community/components/user-comment-reply/user-comment-reply.css.ts
  apps/client/src/widgets/community/components/user-comment-reply/user-comment-reply.tsx
  apps/client/src/widgets/community/components/user-comment/user-comment.tsx
  apps/client/src/widgets/community/constant/mock-user-comment-reply.ts
  packages/bds-ui/src/icons/assets/recomment_line.svg
  packages/bds-ui/src/icons/icon-list.ts
Labels: 💡 Feature, 정훈 🦁

#421 Feat(client): 글 수정 시 카테고리 기능 추가
  apps/client/src/pages/community/community-edit/community-edit.css.ts
  apps/client/src/pages/community/community-edit/community-edit.tsx
  apps/client/src/pages/community/community-write/community-write.tsx
  apps/client/src/shared/types/schema.d.ts
  apps/client/src/widgets/community/components/feed-content/feed-content.tsx
  apps/client/src/widgets/community/components/filter-dropdown/filter-dropdown.css.ts
Labels: 💡 Feature, 민정 🎱

#427 Refactor(client): 온보딩페이지 기본정보 변경사항 적용
  apps/client/src/pages/onboarding/onboarding-page.tsx
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.css.ts
  apps/client/src/widgets/onboarding/components/basic-info-section/basic-info-section.tsx
  apps/client/src/widgets/onboarding/schemas/onboarding-form-schema.ts
  packages/bds-ui/src/components/input/input.css.ts
  packages/bds-ui/src/components/input/input.stories.tsx
  packages/bds-ui/src/components/input/input.tsx
Labels: 혜린 🐧, 🔨 Refactor
